package com.example.todoapp.data.remote

import com.example.todoapp.data.model.TaskRequest
import com.example.todoapp.data.model.TaskResponse
import retrofit2.http.*

/**
 * Task API Service
 *
 * WHAT IS THIS?
 * Retrofit interface that defines all task-related API endpoints.
 * Retrofit will automatically implement this interface for us!
 *
 * WHY SEPARATE FROM UserApiService?
 * - Separation of Concerns: Users vs Tasks are different domains
 * - Single Responsibility: Each service handles one area
 * - Easier to test: Can mock just task operations
 *
 * RETROFIT ANNOTATIONS:
 * @GET = HTTP GET request (fetch data)
 * @POST = HTTP POST request (create data)
 * @PUT = HTTP PUT request (update data)
 * @DELETE = HTTP DELETE request (delete data)
 * @Query = URL query parameter (?userId=5)
 * @Path = URL path parameter (/api/tasks/{id})
 * @Body = JSON body in request
 *
 * AUTHENTICATION:
 * All these endpoints are protected by JWT!
 * AuthInterceptor automatically adds: Authorization: Bearer <token>
 * No need to pass token manually!
 *
 * SUSPEND FUNCTIONS:
 * All functions are 'suspend' = they run in background (coroutines)
 * Must be called from ViewModel's viewModelScope
 */
interface TaskApiService {

    /**
     * Get all tasks for a specific user
     *
     * ENDPOINT: GET /api/tasks?userId={userId}
     *
     * EXAMPLE REQUEST:
     * GET http://192.168.0.129:8081/api/tasks?userId=5
     * Headers: Authorization: Bearer <jwt-token>
     *
     * EXAMPLE RESPONSE:
     * [
     *   {
     *     "id": 1,
     *     "userId": 5,
     *     "title": "Buy groceries",
     *     "description": "Milk, eggs, bread",
     *     "status": "PENDING",
     *     "createdAt": "2025-01-15T10:30:00",
     *     "updatedAt": "2025-01-15T10:30:00"
     *   },
     *   {
     *     "id": 2,
     *     "userId": 5,
     *     "title": "Learn Kotlin",
     *     "description": null,
     *     "status": "IN_PROGRESS",
     *     "createdAt": "2025-01-14T09:00:00",
     *     "updatedAt": "2025-01-15T11:00:00"
     *   }
     * ]
     *
     * @param userId The user's ID to filter tasks
     * @return List of tasks belonging to this user
     *
     * NOTE: Returns empty list if user has no tasks
     */
    @GET("api/tasks")
    suspend fun getTasks(
        @Query("userId") userId: Long
    ): List<TaskResponse>

    /**
     * Get a single task by ID
     *
     * ENDPOINT: GET /api/tasks/{id}
     *
     * EXAMPLE REQUEST:
     * GET http://192.168.0.129:8081/api/tasks/1
     * Headers: Authorization: Bearer <jwt-token>
     *
     * EXAMPLE RESPONSE:
     * {
     *   "id": 1,
     *   "userId": 5,
     *   "title": "Buy groceries",
     *   "description": "Milk, eggs, bread",
     *   "status": "PENDING",
     *   "createdAt": "2025-01-15T10:30:00",
     *   "updatedAt": "2025-01-15T10:30:00"
     * }
     *
     * @param id The task ID
     * @return Single task details
     *
     * ERROR HANDLING:
     * - 404 Not Found: Task doesn't exist
     * - 403 Forbidden: Task belongs to different user
     */
    @GET("api/tasks/{id}")
    suspend fun getTask(
        @Path("id") id: Long
    ): TaskResponse

    /**
     * Create a new task
     *
     * ENDPOINT: POST /api/tasks
     *
     * EXAMPLE REQUEST:
     * POST http://192.168.0.129:8081/api/tasks
     * Headers:
     *   Authorization: Bearer <jwt-token>
     *   Content-Type: application/json
     * Body:
     * {
     *   "userId": 5,
     *   "title": "Complete Kotlin tutorial",
     *   "description": "Learn coroutines and flows",
     *   "status": "PENDING"
     * }
     *
     * EXAMPLE RESPONSE:
     * {
     *   "id": 3,  // ← Generated by database!
     *   "userId": 5,
     *   "title": "Complete Kotlin tutorial",
     *   "description": "Learn coroutines and flows",
     *   "status": "PENDING",
     *   "createdAt": "2025-01-15T12:00:00",  // ← Generated by server!
     *   "updatedAt": "2025-01-15T12:00:00"   // ← Generated by server!
     * }
     *
     * @param request TaskRequest with task details
     * @return TaskResponse with generated id and timestamps
     *
     * VALIDATION:
     * - Title cannot be empty
     * - UserId must match JWT token's user
     */
    @POST("api/tasks")
    suspend fun createTask(
        @Body request: TaskRequest
    ): TaskResponse

    /**
     * Update an existing task
     *
     * ENDPOINT: PUT /api/tasks/{id}
     *
     * EXAMPLE REQUEST:
     * PUT http://192.168.0.129:8081/api/tasks/1
     * Headers:
     *   Authorization: Bearer <jwt-token>
     *   Content-Type: application/json
     * Body:
     * {
     *   "userId": 5,
     *   "title": "Buy groceries",
     *   "description": "Milk, eggs, bread, cheese",
     *   "status": "COMPLETED"  // ← Changed from PENDING to COMPLETED
     * }
     *
     * EXAMPLE RESPONSE:
     * {
     *   "id": 1,
     *   "userId": 5,
     *   "title": "Buy groceries",
     *   "description": "Milk, eggs, bread, cheese",
     *   "status": "COMPLETED",
     *   "createdAt": "2025-01-15T10:30:00",
     *   "updatedAt": "2025-01-15T15:45:00"  // ← Updated!
     * }
     *
     * @param id The task ID to update
     * @param request TaskRequest with updated details
     * @return TaskResponse with updated data
     *
     * USE CASES:
     * - Mark task as completed
     * - Change task status
     * - Edit title/description
     *
     * ERROR HANDLING:
     * - 404 Not Found: Task doesn't exist
     * - 403 Forbidden: Task belongs to different user
     */
    @PUT("api/tasks/{id}")
    suspend fun updateTask(
        @Path("id") id: Long,
        @Body request: TaskRequest
    ): TaskResponse

    /**
     * Delete a task
     *
     * ENDPOINT: DELETE /api/tasks/{id}
     *
     * EXAMPLE REQUEST:
     * DELETE http://192.168.0.129:8081/api/tasks/1
     * Headers: Authorization: Bearer <jwt-token>
     *
     * EXAMPLE RESPONSE:
     * 204 No Content (successful deletion, no body)
     *
     * @param id The task ID to delete
     *
     * USE CASES:
     * - Remove completed tasks
     * - Delete tasks no longer needed
     *
     * ERROR HANDLING:
     * - 404 Not Found: Task doesn't exist
     * - 403 Forbidden: Task belongs to different user
     *
     * NOTE: This is permanent deletion!
     * Consider implementing "soft delete" (status=CANCELLED) instead
     */
    @DELETE("api/tasks/{id}")
    suspend fun deleteTask(
        @Path("id") id: Long
    )
}
