package com.example.todoapp.data.model

import kotlinx.serialization.Serializable

/**
 * Task Response
 *
 * WHAT IS THIS?
 * The data structure we RECEIVE from the backend when:
 * - Fetching all tasks: GET /api/tasks?userId={id}
 * - Getting single task: GET /api/tasks/{id}
 * - Creating a task: POST /api/tasks (returns the created task)
 * - Updating a task: PUT /api/tasks/{id} (returns the updated task)
 *
 * WHY SEPARATE FROM REQUEST?
 * Response includes server-generated data:
 * - id: Generated by database
 * - createdAt: Set by server
 * - updatedAt: Set by server
 *
 * Request only includes data WE provide:
 * - title, description, status, userId
 *
 * KOTLIN FEATURES USED:
 * - Data class: Auto-generates equals(), hashCode(), toString(), copy()
 * - Nullable types (String?): Some fields are optional
 * - @Serializable: Auto JSON conversion
 *
 * EXAMPLE JSON:
 * {
 *   "id": 1,
 *   "userId": 5,
 *   "title": "Learn Kotlin",
 *   "description": "Complete Android TODO app",
 *   "status": "IN_PROGRESS",
 *   "createdAt": "2025-01-15T10:30:00",
 *   "updatedAt": "2025-01-15T14:20:00"
 * }
 */
@Serializable
data class TaskResponse(
    /**
     * Task ID (Primary Key)
     * Generated by the database when task is created
     */
    val id: Long,

    /**
     * User ID (Foreign Key)
     * Which user owns this task?
     * Used for filtering: GET /api/tasks?userId={id}
     */
    val userId: Long,

    /**
     * Task Title (Required)
     * Short description of what needs to be done
     * Example: "Buy groceries", "Complete homework"
     */
    val title: String,

    /**
     * Task Description (Optional)
     * Detailed information about the task
     * Can be null if user didn't provide description
     *
     * KOTLIN NULL SAFETY:
     * String? = can be null
     * String = cannot be null (compile error if you try!)
     */
    val description: String? = null,

    /**
     * Task Status
     * Current state: PENDING, IN_PROGRESS, COMPLETED, CANCELLED
     * Uses the TaskStatus enum for type safety
     */
    val status: TaskStatus,

    /**
     * Created Timestamp
     * When was this task created?
     * ISO 8601 format: "2025-01-15T10:30:00"
     *
     * NOTE: We store as String for now
     * Later we could parse to LocalDateTime for date operations
     */
    val createdAt: String,

    /**
     * Updated Timestamp
     * When was this task last modified?
     * ISO 8601 format: "2025-01-15T14:20:00"
     */
    val updatedAt: String
) {
    /**
     * Helper function: Is this task completed?
     *
     * KOTLIN FEATURE - CUSTOM FUNCTIONS IN DATA CLASSES:
     * Data classes can have functions!
     * This makes it easy to check task state in UI
     *
     * Usage in Compose:
     * if (task.isCompleted()) { ... }
     */
    fun isCompleted(): Boolean {
        return status == TaskStatus.COMPLETED
    }

    /**
     * Helper function: Can this task be edited?
     *
     * Business rule: Don't allow editing completed/cancelled tasks
     */
    fun isEditable(): Boolean {
        return status == TaskStatus.PENDING || status == TaskStatus.IN_PROGRESS
    }

    /**
     * Helper function: Get formatted creation date
     *
     * For now returns the raw string
     * TODO: Parse to LocalDateTime and format nicely
     */
    fun formattedCreatedAt(): String {
        return createdAt.take(10)  // "2025-01-15T10:30:00" → "2025-01-15"
    }
}
